name=bb_h263
version=1.0.0
author=Larry Bank
maintainer=Larry Bank
sentence=Optimized H.263 video decoder
paragraph=A fast H.263 video decoder library meant to work on any target system, including microcontrollers. Single H file contains all of the code.
category=Display
url=https://github.com/bitbank2/bb_h263
architectures=*
includes=bb_h263.h
